import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html>
       
      <body className="">
       
        <main >
            {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
